name: OTUS-CPP-2023-12

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v3

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DPATCH_VERSION=${{ github.run_number }}

      - name: Build
        run: cmake --build ${{github.workspace}}/build

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -VV

      - name: Package
        working-directory: ${{github.workspace}}/build
        run: cpack -VV

      - name: Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false
          title: Release ${{ github.run_number }}
          automatic_release_tag: ${{ github.run_number }}
          files: ${{github.workspace}}/build/helloworld-0.0.${{ github.run_number }}-Linux.deb
