name: OTUS-CPP-2023-12

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DPATCH_VERSION=${{ github.run_number }}

      - name: Build
        run: cmake --build ${{github.workspace}}/build

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -VV

      - name: Package
        working-directory: ${{github.workspace}}/build
        run: cpack -VV

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./helloworld-0.0.${{ github.run_number }}-Linux.deb
          token: ${{ secrets.RELEASE_TOKEN }}
          draft: false
          prerelease: false
          name: Release ${{ github.run_number }}
          tag_name: ${{ github.run_number }}
